-- V1: schema ban đầu (theo docs/PROJECT_SPEC.md mục 4)

CREATE TABLE product (
  id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku    VARCHAR2(64)  NOT NULL UNIQUE,
  name   VARCHAR2(255) NOT NULL,
  price  NUMBER(18,2)  NOT NULL
);

CREATE TABLE stock (
  product_id  NUMBER PRIMARY KEY REFERENCES product(id),
  available   NUMBER(10) NOT NULL CHECK (available >= 0),
  reserved    NUMBER(10) DEFAULT 0 NOT NULL CHECK (reserved >= 0),
  version     NUMBER(10) DEFAULT 0 NOT NULL
);

CREATE TABLE reservation (
  id          VARCHAR2(64) PRIMARY KEY,
  order_id    VARCHAR2(64) NOT NULL,
  product_id  NUMBER NOT NULL REFERENCES product(id),
  qty         NUMBER(10) NOT NULL,
  status      VARCHAR2(16) NOT NULL,
  created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_reservation UNIQUE (order_id, product_id),
  CONSTRAINT ck_reservation_status CHECK (status IN ('RESERVED', 'RELEASED', 'CONFIRMED'))
);

CREATE TABLE orders (
  id               VARCHAR2(64) PRIMARY KEY,
  user_id          VARCHAR2(64)  NOT NULL,
  status           VARCHAR2(16)  NOT NULL,
  total            NUMBER(18,2)  NOT NULL,
  idempotency_key  VARCHAR2(128) NOT NULL,
  created_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_order_idem UNIQUE (user_id, idempotency_key),
  CONSTRAINT ck_orders_status CHECK (status IN ('PENDING', 'CONFIRMED', 'FAILED', 'CANCELLED'))
);

CREATE TABLE order_item (
  order_id    VARCHAR2(64) NOT NULL REFERENCES orders(id),
  product_id  NUMBER NOT NULL REFERENCES product(id),
  qty         NUMBER(10)   NOT NULL,
  price       NUMBER(18,2) NOT NULL,
  PRIMARY KEY (order_id, product_id)
);

CREATE TABLE outbox_events (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aggregate_id  VARCHAR2(64) NOT NULL,
  event_type    VARCHAR2(64) NOT NULL,
  payload       CLOB NOT NULL,
  status        VARCHAR2(16) DEFAULT 'NEW' NOT NULL,
  attempts      NUMBER(5) DEFAULT 0 NOT NULL,
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  sent_at       TIMESTAMP,
  CONSTRAINT ck_outbox_status CHECK (status IN ('NEW', 'SENT', 'FAILED'))
);

CREATE INDEX ix_outbox_status ON outbox_events(status, id);
