-- V4: retry bookkeeping for the outbox worker, and the notification service's inbox + sent notifications.

ALTER TABLE outbox_events ADD (next_attempt_at TIMESTAMP, last_error VARCHAR2(500));

-- Lets the worker check "is there an older unsent event for this aggregate?" cheaply (keeps per-order event order).
CREATE INDEX ix_outbox_aggregate ON outbox_events(aggregate_id, status, id);

-- Inbox: one row per consumed event id. The primary key makes processing idempotent.
CREATE TABLE processed_events (
  event_id      NUMBER NOT NULL,
  consumer      VARCHAR2(64) NOT NULL,
  processed_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_processed_events PRIMARY KEY (consumer, event_id)
);

-- What the (simulated) email/SMS gateway "sent".
CREATE TABLE notifications (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id    NUMBER NOT NULL,
  order_id    VARCHAR2(64) NOT NULL,
  user_id     VARCHAR2(64) NOT NULL,
  channel     VARCHAR2(16) NOT NULL,
  message     VARCHAR2(500) NOT NULL,
  created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX ix_notifications_event ON notifications(event_id);
